const mongoose = require("mongoose");

/*
This code defines a Mongoose schema for order with required fields for paymentId, orderId, status, userId,
 where userId references a User model. Then, it creates a Mongoose model named "Expense" based on this schema.
*/

const OrderSchema = new mongoose.Schema({
  paymentId: {
    type: String,
  },
  orderId: {
    type: String,
    required: true,
  },
  status: {
    type: String,
    required: true,
  },
  /*
  The userId field in the ResetPassword schema references the User model, 
  as indicated by 'ref: "User"'. mongoose.Schema.Types.ObjectId represents 
  a unique identifier generated by MongoDB for each document in a collection.
*/
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
});

const Order = mongoose.model("Order", OrderSchema);

module.exports = Order;
